version: '3.6'
services:
  mysql-a:
    image: mysql:8.4
    container_name: ticketing
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ticketing
      MYSQL_USER: ticketing
      MYSQL_PASSWORD: ticketing-password
      MYSQL_ROOT_PASSWORD: root-password
    volumes:
      - mysql-a-data:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: user
    ports:
      - "5672:5672"
  mysql-issue:
    image: mysql:8.4
    container_name: ticketing-issue
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ticketing-issue
      MYSQL_USER: ticketing
      MYSQL_PASSWORD: ticketing-password
      MYSQL_ROOT_PASSWORD: root-password
    volumes:
      - mysql-issue-data:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: user
    ports:
      - "5672:5672"
volumes:
  mysql-a-data:
  mysql-issue-data:
